"""create_ai_reports_table

Revision ID: 34adbca8c2a5
Revises: 451e7717c1b6
Create Date: 2026-07-18 16:12:28.617774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34adbca8c2a5'
down_revision: Union[str, Sequence[str], None] = '451e7717c1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('related_job_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('input_hash', sa.String(), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reports_id'), 'ai_reports', ['id'], unique=False)
    op.create_index(op.f('ix_ai_reports_input_hash'), 'ai_reports', ['input_hash'], unique=False)
    op.create_index(op.f('ix_ai_reports_related_job_id'), 'ai_reports', ['related_job_id'], unique=False)
    op.create_index(op.f('ix_ai_reports_user_id'), 'ai_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_reports_user_id'), table_name='ai_reports')
    op.drop_index(op.f('ix_ai_reports_related_job_id'), table_name='ai_reports')
    op.drop_index(op.f('ix_ai_reports_input_hash'), table_name='ai_reports')
    op.drop_index(op.f('ix_ai_reports_id'), table_name='ai_reports')
    op.drop_table('ai_reports')
    # ### end Alembic commands ###
